default:
  image: gcc:latest
  # before_script:
  #   - apt-get update
  #   - apt-get install -y build-essential

stages:
  - build
  - test

build:
  tags:
    - linux
  script:
    - make

test:
  tags:
    - linux
  script:
    - make run_test
