default:
  image: gcc:latest
  # before_script:
  #   - apt-get update
  #   - apt-get install -y build-essential

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build
  - test

build:
  tags:
    - linux
  script:
    - make

test:
  tags:
    - linux
  script:
    - make run_test
